export enum AccountingAccount {
  RENT_INCOME = 'RENT_INCOME',
  TENANT_CREDIT_LIABILITY = 'TENANT_CREDIT_LIABILITY',
  SECURITY_DEPOSIT_LIABILITY = 'SECURITY_DEPOSIT_LIABILITY',
  CASH = 'CASH',
  FEES_INCOME = 'FEES_INCOME',
}
