import { MigrationInterface, QueryRunner } from "typeorm";

export class AddResetPasswordColumns1771077666074 implements MigrationInterface {
    name = 'AddResetPasswordColumns1771077666074'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_paymentMethod"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_payments_rent_cycle"`);
        await queryRunner.query(`ALTER TABLE "rent_cycle_line_items" DROP CONSTRAINT "FK_rent_cycle_line_items_rent_cycle"`);
        await queryRunner.query(`ALTER TABLE "rent_cycles" DROP CONSTRAINT "FK_rent_cycles_lease"`);
        await queryRunner.query(`ALTER TABLE "company_settings" DROP CONSTRAINT "FK_company_settings_company"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payment_methods_companyId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payment_methods_isGlobal"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_payment_methods_global_code"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_payment_methods_company_name"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_dueDate"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_status_dueDate"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_rentCycleId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payments_paymentMethodId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_rent_cycle_line_items_rentCycleId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_rent_cycles_leaseId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_rent_cycles_companyId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_rent_cycles_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_rent_cycles_period"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_rent_cycles_dueDate"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_rent_cycles_company_tenant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_rent_cycles_lease_dueDate"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_expenses_companyId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_expenses_propertyId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_expenses_leaseId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_expenses_category"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_expenses_expenseDate"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_expenses_companyId_expenseDate"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_company_settings_companyId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_revoked_refresh_tokens_expiresAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_accounting_entries_companyId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_accounting_entries_leaseId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_accounting_entries_tenantId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_accounting_entries_entryDate"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_accounting_entries_reference"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "CK_expenses_amount_positive"`);
        await queryRunner.query(`ALTER TABLE "accounting_entries" DROP CONSTRAINT "CK_accounting_entries_amount_positive"`);
        await queryRunner.query(`ALTER TABLE "rent_cycles" DROP CONSTRAINT "UQ_rent_cycles_lease_period"`);
        await queryRunner.query(`ALTER TABLE "rent_cycles" DROP CONSTRAINT "UQ_rent_cycles_company_invoice_number"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "resetPasswordToken" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "resetPasswordExpires" TIMESTAMP`);
        await queryRunner.query(`ALTER TYPE "public"."units_leasetype_enum" RENAME TO "units_leasetype_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."units_leasetype_enum" AS ENUM('SHORT_TERM', 'LONG_TERM', 'FIXED_TERM', 'MONTH_TO_MONTH')`);
        await queryRunner.query(`ALTER TABLE "units" ALTER COLUMN "leaseType" TYPE "public"."units_leasetype_enum" USING "leaseType"::"text"::"public"."units_leasetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."units_leasetype_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_frequency_enum" RENAME TO "payment_frequency_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leases_paymentfrequency_enum" AS ENUM('MONTHLY', 'WEEKLY', 'BIWEEKLY', 'QUARTERLY', 'YEARLY')`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "paymentFrequency" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "paymentFrequency" TYPE "public"."leases_paymentfrequency_enum" USING "paymentFrequency"::"text"::"public"."leases_paymentfrequency_enum"`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "paymentFrequency" SET DEFAULT 'MONTHLY'`);
        await queryRunner.query(`DROP TYPE "public"."payment_frequency_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."late_fee_type_enum" RENAME TO "late_fee_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."leases_latefeetype_enum" AS ENUM('FIXED', 'PERCENTAGE', 'NONE')`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "lateFeeType" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "lateFeeType" TYPE "public"."leases_latefeetype_enum" USING "lateFeeType"::"text"::"public"."leases_latefeetype_enum"`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "lateFeeType" SET DEFAULT 'FIXED'`);
        await queryRunner.query(`DROP TYPE "public"."late_fee_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "currency" SET DEFAULT 'USD'`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "amountDue" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "currency" SET DEFAULT 'USD'`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "dueDate" DROP DEFAULT`);
        await queryRunner.query(`ALTER TYPE "public"."rent_cycle_line_item_type_enum" RENAME TO "rent_cycle_line_item_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."rent_cycle_line_items_type_enum" AS ENUM('RENT', 'UTILITY', 'PET_RENT', 'MAINTENANCE', 'LATE_FEE', 'DEPOSIT')`);
        await queryRunner.query(`ALTER TABLE "rent_cycle_line_items" ALTER COLUMN "type" TYPE "public"."rent_cycle_line_items_type_enum" USING "type"::"text"::"public"."rent_cycle_line_items_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."rent_cycle_line_item_type_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."expenses_category_enum" RENAME TO "expenses_category_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_category_enum" AS ENUM('MAINTENANCE', 'UTILITIES', 'TAX', 'REPAIR', 'OTHER')`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "category" TYPE "public"."expenses_category_enum" USING "category"::"text"::"public"."expenses_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_category_enum_old"`);
        await queryRunner.query(`ALTER TABLE "company_settings" ALTER COLUMN "defaultCurrency" SET DEFAULT 'USD'`);
        await queryRunner.query(`ALTER TABLE "revoked_refresh_tokens" DROP CONSTRAINT "UQ_revoked_refresh_tokens_jti"`);
        await queryRunner.query(`ALTER TABLE "revoked_refresh_tokens" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "revoked_refresh_tokens" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."accounting_entries_account_enum" RENAME TO "accounting_entries_account_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."accounting_entries_account_enum" AS ENUM('RENT_INCOME', 'TENANT_CREDIT_LIABILITY', 'SECURITY_DEPOSIT_LIABILITY', 'CASH', 'FEES_INCOME')`);
        await queryRunner.query(`ALTER TABLE "accounting_entries" ALTER COLUMN "account" TYPE "public"."accounting_entries_account_enum" USING "account"::"text"::"public"."accounting_entries_account_enum"`);
        await queryRunner.query(`DROP TYPE "public"."accounting_entries_account_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."accounting_entries_direction_enum" RENAME TO "accounting_entries_direction_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."accounting_entries_direction_enum" AS ENUM('DEBIT', 'CREDIT')`);
        await queryRunner.query(`ALTER TABLE "accounting_entries" ALTER COLUMN "direction" TYPE "public"."accounting_entries_direction_enum" USING "direction"::"text"::"public"."accounting_entries_direction_enum"`);
        await queryRunner.query(`DROP TYPE "public"."accounting_entries_direction_enum_old"`);
        await queryRunner.query(`CREATE INDEX "IDX_d1298f61e2704a9bd4fd364105" ON "payment_methods" ("isGlobal") `);
        await queryRunner.query(`CREATE INDEX "IDX_c9136b030564fc0b44a8aac252" ON "payment_methods" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cbe18cae039006a9c217d5a66a" ON "payments" ("paymentMethodId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4de66211282119ea26cbba9955" ON "payments" ("rentCycleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cf3dbea1bedd84d682085cb4a" ON "payments" ("status", "dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_061998dfce064f1da64249b318" ON "payments" ("dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_3291102eda59eb19cdae0b13b0" ON "rent_cycle_line_items" ("rentCycleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_865de4d70ec9172c7e3c43c7fe" ON "rent_cycles" ("leaseId", "dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_335e34cce3c79e36504ad23a90" ON "rent_cycles" ("companyId", "tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f95224aa7d8f4aabd9d9aec5c" ON "rent_cycles" ("dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_d3748e725c0eb0e2a97cad7a06" ON "rent_cycles" ("period") `);
        await queryRunner.query(`CREATE INDEX "IDX_6c37c249bd6c6d3adb04b90789" ON "rent_cycles" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f96b0146d0877ae0ea28dd65d6" ON "rent_cycles" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a9c5458032ed03ed975f6f4b34" ON "rent_cycles" ("leaseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f52fb01c27607bb74ba05abf16" ON "expenses" ("expenseDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_e069bf5f4d4aaab62a84f24ca4" ON "expenses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_9afd7e1819b1bc311c3ab71382" ON "expenses" ("leaseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fab3e414743d311d5e270810dd" ON "expenses" ("propertyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d94bd2d2e22b7a3192c7389782" ON "expenses" ("companyId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_474a36aafd4ff4a422eab6a3a9" ON "company_settings" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a0d1ffa273d5ef1cfcd10b131e" ON "revoked_refresh_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9fbcc5bbe3a025c048dec0f11b" ON "revoked_refresh_tokens" ("jti") `);
        await queryRunner.query(`CREATE INDEX "IDX_7555313a9e4377650af6af9de0" ON "accounting_entries" ("referenceType", "referenceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0715f2b3a02324e08ef4b027d2" ON "accounting_entries" ("entryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_1df8e2b8765e0a6ed8eec9c80b" ON "accounting_entries" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0e74318eef5568da442dccb7a9" ON "accounting_entries" ("leaseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e49739889e3f3877c53da13e50" ON "accounting_entries" ("companyId") `);
        await queryRunner.query(`ALTER TABLE "rent_cycles" ADD CONSTRAINT "UQ_460553c9ed69e1be45b26b41aed" UNIQUE ("companyId", "invoiceNumber")`);
        await queryRunner.query(`ALTER TABLE "rent_cycles" ADD CONSTRAINT "UQ_dab5907fc83a860ea083ca1e75e" UNIQUE ("leaseId", "period")`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_cbe18cae039006a9c217d5a66a6" FOREIGN KEY ("paymentMethodId") REFERENCES "payment_methods"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_4de66211282119ea26cbba9955a" FOREIGN KEY ("rentCycleId") REFERENCES "rent_cycles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rent_cycle_line_items" ADD CONSTRAINT "FK_3291102eda59eb19cdae0b13b09" FOREIGN KEY ("rentCycleId") REFERENCES "rent_cycles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rent_cycles" ADD CONSTRAINT "FK_a9c5458032ed03ed975f6f4b348" FOREIGN KEY ("leaseId") REFERENCES "leases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_settings" ADD CONSTRAINT "FK_474a36aafd4ff4a422eab6a3a9d" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "company_settings" DROP CONSTRAINT "FK_474a36aafd4ff4a422eab6a3a9d"`);
        await queryRunner.query(`ALTER TABLE "rent_cycles" DROP CONSTRAINT "FK_a9c5458032ed03ed975f6f4b348"`);
        await queryRunner.query(`ALTER TABLE "rent_cycle_line_items" DROP CONSTRAINT "FK_3291102eda59eb19cdae0b13b09"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_4de66211282119ea26cbba9955a"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_cbe18cae039006a9c217d5a66a6"`);
        await queryRunner.query(`ALTER TABLE "rent_cycles" DROP CONSTRAINT "UQ_dab5907fc83a860ea083ca1e75e"`);
        await queryRunner.query(`ALTER TABLE "rent_cycles" DROP CONSTRAINT "UQ_460553c9ed69e1be45b26b41aed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e49739889e3f3877c53da13e50"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e74318eef5568da442dccb7a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1df8e2b8765e0a6ed8eec9c80b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0715f2b3a02324e08ef4b027d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7555313a9e4377650af6af9de0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fbcc5bbe3a025c048dec0f11b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a0d1ffa273d5ef1cfcd10b131e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_474a36aafd4ff4a422eab6a3a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d94bd2d2e22b7a3192c7389782"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fab3e414743d311d5e270810dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9afd7e1819b1bc311c3ab71382"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e069bf5f4d4aaab62a84f24ca4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f52fb01c27607bb74ba05abf16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9c5458032ed03ed975f6f4b34"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f96b0146d0877ae0ea28dd65d6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c37c249bd6c6d3adb04b90789"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d3748e725c0eb0e2a97cad7a06"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f95224aa7d8f4aabd9d9aec5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_335e34cce3c79e36504ad23a90"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_865de4d70ec9172c7e3c43c7fe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3291102eda59eb19cdae0b13b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_061998dfce064f1da64249b318"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cf3dbea1bedd84d682085cb4a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4de66211282119ea26cbba9955"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cbe18cae039006a9c217d5a66a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9136b030564fc0b44a8aac252"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1298f61e2704a9bd4fd364105"`);
        await queryRunner.query(`CREATE TYPE "public"."accounting_entries_direction_enum_old" AS ENUM('DEBIT', 'CREDIT')`);
        await queryRunner.query(`ALTER TABLE "accounting_entries" ALTER COLUMN "direction" TYPE "public"."accounting_entries_direction_enum_old" USING "direction"::"text"::"public"."accounting_entries_direction_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."accounting_entries_direction_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."accounting_entries_direction_enum_old" RENAME TO "accounting_entries_direction_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."accounting_entries_account_enum_old" AS ENUM('RENT_INCOME', 'TENANT_CREDIT_LIABILITY', 'SECURITY_DEPOSIT_LIABILITY', 'CASH', 'FEES_INCOME')`);
        await queryRunner.query(`ALTER TABLE "accounting_entries" ALTER COLUMN "account" TYPE "public"."accounting_entries_account_enum_old" USING "account"::"text"::"public"."accounting_entries_account_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."accounting_entries_account_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."accounting_entries_account_enum_old" RENAME TO "accounting_entries_account_enum"`);
        await queryRunner.query(`ALTER TABLE "revoked_refresh_tokens" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "revoked_refresh_tokens" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "revoked_refresh_tokens" ADD CONSTRAINT "UQ_revoked_refresh_tokens_jti" UNIQUE ("jti")`);
        await queryRunner.query(`ALTER TABLE "company_settings" ALTER COLUMN "defaultCurrency" SET DEFAULT 'KES'`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_category_enum_old" AS ENUM('MAINTENANCE', 'UTILITIES', 'TAX', 'REPAIR', 'OTHER')`);
        await queryRunner.query(`ALTER TABLE "expenses" ALTER COLUMN "category" TYPE "public"."expenses_category_enum_old" USING "category"::"text"::"public"."expenses_category_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_category_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."expenses_category_enum_old" RENAME TO "expenses_category_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."rent_cycle_line_item_type_enum_old" AS ENUM('RENT', 'UTILITY', 'PET_RENT', 'MAINTENANCE', 'LATE_FEE')`);
        await queryRunner.query(`ALTER TABLE "rent_cycle_line_items" ALTER COLUMN "type" TYPE "public"."rent_cycle_line_item_type_enum_old" USING "type"::"text"::"public"."rent_cycle_line_item_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."rent_cycle_line_items_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."rent_cycle_line_item_type_enum_old" RENAME TO "rent_cycle_line_item_type_enum"`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "dueDate" SET DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "currency" SET DEFAULT 'KES'`);
        await queryRunner.query(`ALTER TABLE "payments" ALTER COLUMN "amountDue" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "currency" SET DEFAULT 'KES'`);
        await queryRunner.query(`CREATE TYPE "public"."late_fee_type_enum_old" AS ENUM('FIXED', 'PERCENTAGE', 'NONE')`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "lateFeeType" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "lateFeeType" TYPE "public"."late_fee_type_enum_old" USING "lateFeeType"::"text"::"public"."late_fee_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "lateFeeType" SET DEFAULT 'FIXED'`);
        await queryRunner.query(`DROP TYPE "public"."leases_latefeetype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."late_fee_type_enum_old" RENAME TO "late_fee_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_frequency_enum_old" AS ENUM('MONTHLY', 'WEEKLY', 'BIWEEKLY', 'QUARTERLY', 'YEARLY')`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "paymentFrequency" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "paymentFrequency" TYPE "public"."payment_frequency_enum_old" USING "paymentFrequency"::"text"::"public"."payment_frequency_enum_old"`);
        await queryRunner.query(`ALTER TABLE "leases" ALTER COLUMN "paymentFrequency" SET DEFAULT 'MONTHLY'`);
        await queryRunner.query(`DROP TYPE "public"."leases_paymentfrequency_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_frequency_enum_old" RENAME TO "payment_frequency_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."units_leasetype_enum_old" AS ENUM('SHORT_TERM', 'LONG_TERM', 'MONTH_TO_MONTH')`);
        await queryRunner.query(`ALTER TABLE "units" ALTER COLUMN "leaseType" TYPE "public"."units_leasetype_enum_old" USING "leaseType"::"text"::"public"."units_leasetype_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."units_leasetype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."units_leasetype_enum_old" RENAME TO "units_leasetype_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "resetPasswordExpires"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "resetPasswordToken"`);
        await queryRunner.query(`ALTER TABLE "rent_cycles" ADD CONSTRAINT "UQ_rent_cycles_company_invoice_number" UNIQUE ("companyId", "invoiceNumber")`);
        await queryRunner.query(`ALTER TABLE "rent_cycles" ADD CONSTRAINT "UQ_rent_cycles_lease_period" UNIQUE ("leaseId", "period")`);
        await queryRunner.query(`ALTER TABLE "accounting_entries" ADD CONSTRAINT "CK_accounting_entries_amount_positive" CHECK ((amount > (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "CK_expenses_amount_positive" CHECK ((amount > (0)::numeric))`);
        await queryRunner.query(`CREATE INDEX "IDX_accounting_entries_reference" ON "accounting_entries" ("referenceId", "referenceType") `);
        await queryRunner.query(`CREATE INDEX "IDX_accounting_entries_entryDate" ON "accounting_entries" ("entryDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_accounting_entries_tenantId" ON "accounting_entries" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_accounting_entries_leaseId" ON "accounting_entries" ("leaseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_accounting_entries_companyId" ON "accounting_entries" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_revoked_refresh_tokens_expiresAt" ON "revoked_refresh_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_company_settings_companyId" ON "company_settings" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_expenses_companyId_expenseDate" ON "expenses" ("companyId", "expenseDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_expenses_expenseDate" ON "expenses" ("expenseDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_expenses_category" ON "expenses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_expenses_leaseId" ON "expenses" ("leaseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_expenses_propertyId" ON "expenses" ("propertyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_expenses_companyId" ON "expenses" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_rent_cycles_lease_dueDate" ON "rent_cycles" ("dueDate", "leaseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_rent_cycles_company_tenant" ON "rent_cycles" ("companyId", "tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_rent_cycles_dueDate" ON "rent_cycles" ("dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_rent_cycles_period" ON "rent_cycles" ("period") `);
        await queryRunner.query(`CREATE INDEX "IDX_rent_cycles_tenantId" ON "rent_cycles" ("tenantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_rent_cycles_companyId" ON "rent_cycles" ("companyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_rent_cycles_leaseId" ON "rent_cycles" ("leaseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_rent_cycle_line_items_rentCycleId" ON "rent_cycle_line_items" ("rentCycleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_paymentMethodId" ON "payments" ("paymentMethodId") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_rentCycleId" ON "payments" ("rentCycleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_status_dueDate" ON "payments" ("dueDate", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_payments_dueDate" ON "payments" ("dueDate") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_payment_methods_company_name" ON "payment_methods" ("companyId", "name") WHERE ("companyId" IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_payment_methods_global_code" ON "payment_methods" ("code") WHERE ("isGlobal" = true)`);
        await queryRunner.query(`CREATE INDEX "IDX_payment_methods_isGlobal" ON "payment_methods" ("isGlobal") `);
        await queryRunner.query(`CREATE INDEX "IDX_payment_methods_companyId" ON "payment_methods" ("companyId") `);
        await queryRunner.query(`ALTER TABLE "company_settings" ADD CONSTRAINT "FK_company_settings_company" FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rent_cycles" ADD CONSTRAINT "FK_rent_cycles_lease" FOREIGN KEY ("leaseId") REFERENCES "leases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rent_cycle_line_items" ADD CONSTRAINT "FK_rent_cycle_line_items_rent_cycle" FOREIGN KEY ("rentCycleId") REFERENCES "rent_cycles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_rent_cycle" FOREIGN KEY ("rentCycleId") REFERENCES "rent_cycles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_payments_paymentMethod" FOREIGN KEY ("paymentMethodId") REFERENCES "payment_methods"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
