import { HttpException, HttpStatus } from '@nestjs/common';
import {
  ERROR_MESSAGES,
  ErrorMessageKey,
} from '../constants/error-messages.constant';

export enum ErrorCode {
  // Authentication
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  INVALID_RESET_TOKEN = 'INVALID_RESET_TOKEN',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  INVALID_VERIFICATION_TOKEN = 'INVALID_VERIFICATION_TOKEN',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  USER_ALREADY_IN_COMPANY = 'USER_ALREADY_IN_COMPANY',
  USER_NOT_IN_COMPANY = 'USER_NOT_IN_COMPANY',

  // Company
  COMPANY_NOT_FOUND = 'COMPANY_NOT_FOUND',
  COMPANY_SLUG_EXISTS = 'COMPANY_SLUG_EXISTS',
  NOT_COMPANY_ADMIN = 'NOT_COMPANY_ADMIN',
  COMPANY_CONTEXT_REQUIRED = 'COMPANY_CONTEXT_REQUIRED',
  USER_NOT_BELONGS_TO_COMPANY = 'USER_NOT_BELONGS_TO_COMPANY',

  // Validation
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Permissions
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  NOT_COMPANY_MEMBER = 'NOT_COMPANY_MEMBER',
  ROLE_REQUIRED = 'ROLE_REQUIRED',
  CAN_ONLY_UPDATE_OWN_PROFILE = 'CAN_ONLY_UPDATE_OWN_PROFILE',
  SUPER_ADMIN_ACCESS_DENIED = 'SUPER_ADMIN_ACCESS_DENIED',
  CANNOT_REMOVE_LAST_SUPER_ADMIN = 'CANNOT_REMOVE_LAST_SUPER_ADMIN',

  // Invitations
  INVITATION_NOT_FOUND = 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED = 'INVITATION_EXPIRED',
  INVITATION_ALREADY_ACCEPTED = 'INVITATION_ALREADY_ACCEPTED',
  INVITATION_ALREADY_CANCELLED = 'INVITATION_ALREADY_CANCELLED',
  USER_ALREADY_INVITED = 'USER_ALREADY_INVITED',
  INVALID_INVITATION_TOKEN = 'INVALID_INVITATION_TOKEN',

  // Property
  PROPERTY_NOT_FOUND = 'PROPERTY_NOT_FOUND',

  // Unit
  UNIT_NOT_FOUND = 'UNIT_NOT_FOUND',
  UNIT_NUMBER_EXISTS = 'UNIT_NUMBER_EXISTS',

  // Tenant
  TENANT_NOT_FOUND = 'TENANT_NOT_FOUND',
  TENANT_ALREADY_EXISTS = 'TENANT_ALREADY_EXISTS',
  TENANT_INVITATION_NOT_FOUND = 'TENANT_INVITATION_NOT_FOUND',
  TENANT_INVITATION_EXPIRED = 'TENANT_INVITATION_EXPIRED',
  TENANT_INVITATION_ALREADY_ACCEPTED = 'TENANT_INVITATION_ALREADY_ACCEPTED',
  CAN_ONLY_VIEW_OWN_TENANT_DATA = 'CAN_ONLY_VIEW_OWN_TENANT_DATA',
  CAN_ONLY_VIEW_INVOICES_FOR_OWN_LEASES = 'CAN_ONLY_VIEW_INVOICES_FOR_OWN_LEASES',
  CAN_ONLY_VIEW_OWN_INVOICES = 'CAN_ONLY_VIEW_OWN_INVOICES',

  // Lease
  LEASE_NOT_FOUND = 'LEASE_NOT_FOUND',
  UNIT_ALREADY_LEASED = 'UNIT_ALREADY_LEASED',
  CANNOT_DELETE_ACTIVE_LEASE = 'CANNOT_DELETE_ACTIVE_LEASE',
  CANNOT_UPDATE_ACTIVE_LEASE_FIELD = 'CANNOT_UPDATE_ACTIVE_LEASE_FIELD',
  INVALID_LEASE_DATES = 'INVALID_LEASE_DATES',
  LEASE_ALREADY_ACTIVE = 'LEASE_ALREADY_ACTIVE',
  LEASE_NOT_ACTIVE = 'LEASE_NOT_ACTIVE',
  CANNOT_ACTIVATE_UNAVAILABLE_UNIT = 'CANNOT_ACTIVATE_UNAVAILABLE_UNIT',

  // Payment
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_ALREADY_COMPLETED = 'PAYMENT_ALREADY_COMPLETED',
  CANNOT_EDIT_COMPLETED_PAYMENT = 'CANNOT_EDIT_COMPLETED_PAYMENT',
  INVALID_PAYMENT_STATUS_TRANSITION = 'INVALID_PAYMENT_STATUS_TRANSITION',
  LEASE_NOT_FOUND_FOR_PAYMENT = 'LEASE_NOT_FOUND_FOR_PAYMENT',
  TENANT_NOT_FOUND_FOR_PAYMENT = 'TENANT_NOT_FOUND_FOR_PAYMENT',
  CANNOT_DELETE_COMPLETED_PAYMENT = 'CANNOT_DELETE_COMPLETED_PAYMENT',
  CANNOT_REVERSE_PAYMENT = 'CANNOT_REVERSE_PAYMENT',
  PAYMENT_CREATE_ROLE_REQUIRED = 'PAYMENT_CREATE_ROLE_REQUIRED',
  PAYMENT_DATE_IN_FUTURE = 'PAYMENT_DATE_IN_FUTURE',
  PAYMENT_VOID_INVOICE = 'PAYMENT_VOID_INVOICE',
  PAYMENT_NON_DEPOSIT_ON_DEPOSIT_INVOICE = 'PAYMENT_NON_DEPOSIT_ON_DEPOSIT_INVOICE',
  PAYMENT_NON_UTILITY_ON_UTILITY_INVOICE = 'PAYMENT_NON_UTILITY_ON_UTILITY_INVOICE',
  PAYMENT_DEPOSIT_ON_RENT_INVOICE = 'PAYMENT_DEPOSIT_ON_RENT_INVOICE',
  PAYMENT_UTILITY_ON_RENT_INVOICE = 'PAYMENT_UTILITY_ON_RENT_INVOICE',
  RENT_CYCLE_NOT_FOUND_OR_LEASE_MISMATCH = 'RENT_CYCLE_NOT_FOUND_OR_LEASE_MISMATCH',
  PAYMENT_UPDATE_ROLE_REQUIRED = 'PAYMENT_UPDATE_ROLE_REQUIRED',
  PAYMENT_RECORD_ROLE_REQUIRED = 'PAYMENT_RECORD_ROLE_REQUIRED',
  PAYMENT_AMOUNT_MUST_BE_POSITIVE = 'PAYMENT_AMOUNT_MUST_BE_POSITIVE',
  PAYMENT_REVERSE_ROLE_REQUIRED = 'PAYMENT_REVERSE_ROLE_REQUIRED',
  PAYMENT_MARK_FAILED_ROLE_REQUIRED = 'PAYMENT_MARK_FAILED_ROLE_REQUIRED',
  PAYMENT_DELETE_ROLE_REQUIRED = 'PAYMENT_DELETE_ROLE_REQUIRED',
  PAYMENT_MARK_FAILED_PENDING_ONLY = 'PAYMENT_MARK_FAILED_PENDING_ONLY',
  PAYMENT_TENANT_OR_LEASE_REQUIRED = 'PAYMENT_TENANT_OR_LEASE_REQUIRED',
  PAYMENT_VIEW_OWN_ONLY = 'PAYMENT_VIEW_OWN_ONLY',
  PAYMENT_METHOD_NOT_FOUND = 'PAYMENT_METHOD_NOT_FOUND',
  PAYMENT_METHOD_COMPANY_MISMATCH = 'PAYMENT_METHOD_COMPANY_MISMATCH',
  PAYMENT_METHOD_REQUIRED = 'PAYMENT_METHOD_REQUIRED',
  PAYMENT_ALREADY_FULLY_PAID = 'PAYMENT_ALREADY_FULLY_PAID',
  PAYMENT_AMOUNT_EXCEEDS_DUE = 'PAYMENT_AMOUNT_EXCEEDS_DUE',

  // Rent cycle
  RENT_CYCLE_NOT_FOUND = 'RENT_CYCLE_NOT_FOUND',
  RENT_CYCLE_ALREADY_EXISTS_FOR_PERIOD = 'RENT_CYCLE_ALREADY_EXISTS_FOR_PERIOD',
  INVOICE_NUMBER_GENERATION_FAILED = 'INVOICE_NUMBER_GENERATION_FAILED',
  INVOICE_NUMBER_GENERATION_FAILED_FALLBACK = 'INVOICE_NUMBER_GENERATION_FAILED_FALLBACK',
  INVOICE_NUMBER_CONFLICT_RETRY = 'INVOICE_NUMBER_CONFLICT_RETRY',
  LATE_FEES_DISABLED_FOR_COMPANY = 'LATE_FEES_DISABLED_FOR_COMPANY',
  LATE_FEE_ALREADY_APPLIED = 'LATE_FEE_ALREADY_APPLIED',
  INVOICE_ALREADY_VOIDED = 'INVOICE_ALREADY_VOIDED',
  CANNOT_VOID_INVOICE_WITH_ACTIVE_PAYMENTS = 'CANNOT_VOID_INVOICE_WITH_ACTIVE_PAYMENTS',
  INVALID_BILLING_PERIOD_FORMAT = 'INVALID_BILLING_PERIOD_FORMAT',
  RENT_CYCLE_CLOSED = 'RENT_CYCLE_CLOSED',

  // Water / utility
  WATER_METER_NOT_FOUND = 'WATER_METER_NOT_FOUND',
  WATER_DISABLED_FOR_PROPERTY = 'WATER_DISABLED_FOR_PROPERTY',
  WATER_UTILITIES_INCLUDED = 'WATER_UTILITIES_INCLUDED',
  WATER_LEASE_INACTIVE_FOR_READING = 'WATER_LEASE_INACTIVE_FOR_READING',
  WATER_NO_ACTIVE_TENANT = 'WATER_NO_ACTIVE_TENANT',
  WATER_MISSING_INITIAL_READING = 'WATER_MISSING_INITIAL_READING',
  INVALID_METER_READING = 'INVALID_METER_READING',
  WATER_RATE_NOT_CONFIGURED = 'WATER_RATE_NOT_CONFIGURED',
  WATER_DUPLICATE_READING_SAME_DATE = 'WATER_DUPLICATE_READING_SAME_DATE',
  UTILITY_NOT_ALLOWED_ON_DEPOSIT = 'UTILITY_NOT_ALLOWED_ON_DEPOSIT',
  UTILITY_ACCESS_DENIED = 'UTILITY_ACCESS_DENIED',

  // General
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
}

export interface ErrorDetails {
  field?: string;
  value?: any;
  fields?: Array<{
    field: string;
    message: string;
    value?: any;
  }>;
  [key: string]: any;
}

export class BusinessException extends HttpException {
  constructor(
    public readonly errorCode: ErrorCode,
    message?: string,
    statusCode: HttpStatus = HttpStatus.BAD_REQUEST,
    public readonly details?: ErrorDetails,
  ) {
    const errorMessage =
      message ||
      ERROR_MESSAGES[errorCode as ErrorMessageKey] ||
      'An error occurred';
    super(
      {
        errorCode,
        message: errorMessage,
        details: details || {},
      },
      statusCode,
    );
  }
}
