export enum UnitType {
  STUDIO = 'STUDIO',
  ONE_BEDROOM = 'ONE_BEDROOM',
  TWO_BEDROOM = 'TWO_BEDROOM',
  THREE_BEDROOM = 'THREE_BEDROOM',
  FOUR_PLUS_BEDROOM = 'FOUR_PLUS_BEDROOM',
  SHOP = 'SHOP',
  COMMERCIAL = 'COMMERCIAL',
  STORAGE = 'STORAGE',
  PARKING = 'PARKING',
  PENTHOUSE = 'PENTHOUSE',
}

